### ISSUE TITLE
Preprocess error

### ISSUE THREAD

**Issue by Stardust-minus** [keonlee9420/Comprehensive-Transformer-TTS#17]
█████████| 137/137 [18:49:05<00:00, 494.49s/it]                                          
Computing statistic quantities ...                                                       
 Traceback (most recent call last):                                                          
File "preprocess.py", line 19, in <module>                                                  
preprocessor.build_from_path()                                                         
 File "/GPUFS/sysu_hpcedu_123/Comprehensive-Transformer-TTS/preprocessor/preprocessor.py", line 267, in build_from_path
 f0s_sup_stats = compute_f0_stats(f0s_sup)                                               
File "/GPUFS/sysu_hpcedu_123/Comprehensive-Transformer-TTS/preprocessor/preprocessor.py", line 145, in compute_f0_stats                                                               return (f0_mean, f0_std)
UnboundLocalError: local variable 'f0_mean' referenced before assignment

It crashed after a long time I run prerprocess
For dataset,I use a dataset which simliar as VCTK but chinese,and It did not throw any error before this step.
Could anyone can help me?

**Comment by yihaoyao402** [comment]
i met the same problem, do you have the way to solve? 3q

**Comment by Stardust-minus** [comment]
> i met the same problem, do you have the way to solve? 3q

Not at all，I cant find where the problem is
